version: '3.1'

services:
  rest:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: "db:5432"
      DB_NAME: &dbName "hbcdb"
      DB_USER: &dbUser "root"
      DB_PASSWORD: &dbPassword "password"
  #    restart: always
  db:
    image: postgres:13.3
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: *dbName
      POSTGRES_USER: *dbUser
      POSTGRES_PASSWORD: *dbPassword

volumes:
  postgres-data: